const APP = {
  user: {
    name: 'Dr. Alejandro Torres',
    initials: 'AT',
    specialty: 'Oncología',
    subspecialty: 'Oncología Torácica',
    institution: 'Clínica Santa Isabel',
    city: 'Buenos Aires',
    province: 'Buenos Aires',
    country: 'Argentina',
    matricula: 'MN 87.654',
    verified: true,
  },

  specialties: [
    'Oncología', 'Hematología', 'Medicina Interna', 'Neurología',
    'Cardiología', 'Pediatría', 'Ginecología', 'Neumología',
    'Gastroenterología', 'Endocrinología', 'Reumatología', 'Infectología',
    'Nefrología', 'Clínica Médica',
  ],

  provinces: [
    'Buenos Aires', 'CABA', 'Córdoba', 'Santa Fe', 'Mendoza',
    'Tucumán', 'Rosario', 'Neuquén', 'Salta', 'Misiones',
  ],

  trials: [
    {
      id: 1,
      name: 'DESTINY-Lung05',
      fullName: 'Trastuzumab Deruxtecan vs Quimioterapia en CPNM HER2+',
      sponsor: 'AstraZeneca',
      sponsorInitials: 'AZ',
      phase: 'Fase III',
      pathology: 'Cáncer de Pulmón',
      specialty: 'Oncología',
      status: 'reclutando',
      center: 'CEMIC',
      city: 'Buenos Aires',
      slots: 3,
      hasFee: true,
      feeAmount: 500,
      feeNote: 'USD 500 por paciente que ingresa a screening',
      coordinator: {
        name: 'Lic. María Fernández',
        initials: 'MF',
        center: 'CEMIC — Centro de Investigación Clínica',
        responseTime: '< 24 hs',
      },
      criteria: {
        inclusion: [
          'CPNM estadio IIIB/IV confirmado histológicamente',
          'Mutación HER2 documentada (NGS o IHC 3+)',
          'ECOG Performance Status 0-2',
          'Al menos 1 línea previa de tratamiento sistémico',
          'Función hepática, renal y hematológica adecuada',
        ],
        exclusion: [
          'Metástasis activas del SNC sin tratamiento previo',
          'Enfermedad pulmonar intersticial activa o antecedente',
          'Otra neoplasia maligna activa en los últimos 3 años',
        ],
      },
      description: 'Estudio internacional de Fase III que compara la eficacia y seguridad de trastuzumab deruxtecan frente a quimioterapia estándar en CPNM avanzado con mutación HER2.',
      openDate: '2025-03-01',
      closingDate: '2026-09-30',
    },
    {
      id: 2,
      name: 'SEQUOIA-2',
      fullName: 'Zanubrutinib vs Ibrutinib en LLC/LCP Recidivante o Refractaria',
      sponsor: 'BeOne Medicines',
      sponsorInitials: 'BO',
      phase: 'Fase III',
      pathology: 'Leucemia / Linfoma',
      specialty: 'Hematología',
      status: 'reclutando',
      center: 'Hospital Italiano de Bs. As.',
      city: 'Buenos Aires',
      slots: 5,
      hasFee: false,
      coordinator: {
        name: 'Dra. Ana Rodríguez',
        initials: 'AR',
        center: 'Servicio de Hematología — HIBA',
        responseTime: '< 48 hs',
      },
      criteria: {
        inclusion: [
          'LLC o linfoma de células del manto confirmado citológicamente',
          'Al menos 1 línea previa que incluya agente anti-CD20',
          'ECOG Performance Status 0-2',
          'Edad ≥ 18 años',
          'Función hepática adecuada (Bilirrubina ≤ 1.5× LSN)',
        ],
        exclusion: [
          'Tratamiento previo con inhibidores de BTK',
          'Transformación a linfoma de Richter activa',
          'Insuficiencia hepática grave (Child-Pugh C)',
        ],
      },
      description: 'Estudio de Fase III que evalúa zanubrutinib frente a ibrutinib en LLC o linfoma de células del manto recidivante o refractario, con foco en el perfil de seguridad cardiovascular.',
      openDate: '2025-06-15',
      closingDate: '2026-12-31',
    },
    {
      id: 3,
      name: 'RUBY',
      fullName: 'Dostarlimab + Carboplatino/Paclitaxel en Cáncer de Endometrio Avanzado',
      sponsor: 'GSK',
      sponsorInitials: 'GK',
      phase: 'Fase III',
      pathology: 'Ginecología Oncológica',
      specialty: 'Oncología',
      status: 'reclutando',
      center: 'Instituto Roffo',
      city: 'Buenos Aires',
      slots: 2,
      hasFee: true,
      feeAmount: 400,
      feeNote: 'USD 400 por paciente randomizado',
      coordinator: {
        name: 'Dra. Laura Gómez',
        initials: 'LG',
        center: 'Instituto Roffo — Oncología Ginecológica',
        responseTime: '< 24 hs',
      },
      criteria: {
        inclusion: [
          'Adenocarcinoma de endometrio estadio III/IV o recidivante',
          'Sin tratamiento sistémico previo para enfermedad avanzada',
          'ECOG Performance Status 0-1',
          'Muestra tumoral disponible para determinación MMR/MSI',
        ],
        exclusion: [
          'Antecedente de enfermedad autoinmune activa en tratamiento',
          'Corticosteroides sistémicos > 10 mg/día equivalente prednisona',
          'Metástasis cerebrales activas o sintomáticas',
        ],
      },
      description: 'Estudio global de Fase III que evalúa dostarlimab (anti-PD-1) combinado con quimioterapia estándar como primera línea en cáncer de endometrio avanzado o recidivante.',
      openDate: '2025-01-10',
      closingDate: '2026-06-30',
    },
    {
      id: 4,
      name: 'COMMANDS',
      fullName: 'Luspatercept vs Eritropoyetina en SMD de Bajo Riesgo con Anemia',
      sponsor: 'Bristol Myers Squibb',
      sponsorInitials: 'BM',
      phase: 'Fase III',
      pathology: 'Síndrome Mielodisplásico',
      specialty: 'Hematología',
      status: 'reclutando',
      center: 'Hospital Británico',
      city: 'Buenos Aires',
      slots: 4,
      hasFee: false,
      coordinator: {
        name: 'Dr. Roberto Díaz',
        initials: 'RD',
        center: 'Servicio de Hematología — Hospital Británico',
        responseTime: '< 72 hs',
      },
      criteria: {
        inclusion: [
          'SMD de bajo riesgo (IPSS-R ≤ 3.5) confirmado por biopsia',
          'Hemoglobina < 10 g/dL con síntomas anémicos',
          'Dependencia transfusional (≥ 2 CH en las 8 semanas previas)',
          'Sin tratamiento previo con agentes estimulantes de eritropoyesis',
        ],
        exclusion: [
          'SMD con exceso de blastos ≥ 5%',
          'Quimioterapia o radioterapia en los últimos 6 meses',
          'Evento trombótico o cardiovascular mayor en últimos 3 meses',
        ],
      },
      description: 'Ensayo de Fase III que compara luspatercept con eritropoyetina en primera línea en SMD de bajo riesgo con anemia dependiente de transfusiones.',
      openDate: '2025-04-20',
      closingDate: '2026-10-15',
    },
    {
      id: 5,
      name: 'TROPION-Lung08',
      fullName: 'Datopotamab Deruxtecan vs Pembrolizumab + Quimioterapia en CPNM',
      sponsor: 'Daiichi Sankyo / AZ',
      sponsorInitials: 'DS',
      phase: 'Fase III',
      pathology: 'Cáncer de Pulmón',
      specialty: 'Oncología',
      status: 'cerrando',
      center: 'Instituto Alexander Fleming',
      city: 'Buenos Aires',
      slots: 1,
      hasFee: true,
      feeAmount: 500,
      feeNote: 'USD 500 por paciente que inicia screening',
      coordinator: {
        name: 'Lic. Carolina Herrera',
        initials: 'CH',
        center: 'Instituto Alexander Fleming — Oncología Clínica',
        responseTime: '< 24 hs',
      },
      criteria: {
        inclusion: [
          'CPNM no escamoso estadio IV confirmado histológicamente',
          'Sin tratamiento sistémico previo para enfermedad metastásica',
          'PD-L1 TPS ≥ 50% por IHC',
          'ECOG Performance Status 0-1',
          'Sin mutación conductora accionable (EGFR, ALK, ROS1, KRAS G12C)',
        ],
        exclusion: [
          'Mutación EGFR sensibilizante, reordenamiento ALK o ROS1',
          'Metástasis cerebrales activas o sintomáticas no tratadas',
          'Enfermedad pulmonar intersticial activa',
        ],
      },
      description: 'Estudio global de Fase III que evalúa datopotamab deruxtecan (DATO-DXd) frente a pembrolizumab + quimioterapia como primera línea en CPNM avanzado con alta expresión de PD-L1.',
      openDate: '2024-11-01',
      closingDate: '2026-05-31',
    },
  ],

  referrals: [
    {
      id: 1,
      trialId: 2,
      trialName: 'SEQUOIA-2',
      patientInitials: 'M.G.',
      patientAge: 67,
      status: 'en_screening',
      date: '2026-04-28',
      notes: 'Paciente masculino con LLC refractaria post-venetoclax. ECOG 1. Sin BTK previo.',
    },
  ],

  messages: {
    2: [
      { sender: 'coordinator', text: 'Hola Dr. Torres, gracias por su consulta sobre SEQUOIA-2. Estaremos encantados de evaluar a su paciente. ¿Podría compartir un resumen clínico?', time: '10:32' },
      { sender: 'user', text: 'Muchas gracias. Paciente masculino, 67 años, LLC refractaria post-venetoclax, ECOG 1. Sin tratamiento previo con inhibidores de BTK.', time: '10:45' },
      { sender: 'coordinator', text: 'Excelente perfil. Cumple los criterios principales. Podemos agendarle una visita de pre-screening para la semana que viene. ¿Le parece bien el martes a las 10?', time: '11:02' },
    ],
  },
};
